- name: Manage VPS Ubuntu
  hosts: Ubuntu
  become: True
  become_user: "{{ become_user }}"
  gather_facts: false
  tasks:
    - name: Test ping
      ping:
    # - name: List the folder
    #   command: ls
    #   register: output
    # - debug: var=output.stdout_lines
    # - name: Copy file
    #   copy:
    #     src: ./note.txt
    #     dest: /home/cpu202/data-disk/temptest/
    #   register: output
    # - debug: var=output.stdout_lines