---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: ansible-awx
stringData:
  host: awx-postgres
  port: "5432"
  database: awx
  username: awx
  password: dtest1010
  type: managed
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: ansible-awx
stringData:
  password: dtest1010
type: Opaque

